[package]
name = "xp"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
bitvec = "1"
either = "1.12.0"
statrs = "0.18.0"
clap = { version = "4.5.43", features = ["derive"] }
minisketch-rs = "0.1"

[lib]
path = "src/lib.rs"

[[bin]]
name = "riblt"
path = "src/bin/riblt.rs"

[[bin]]
name = "rbf_riblt"
path = "src/bin/rbf_riblt.rs"

[[bin]]
name = "bf_riblt"
path = "src/bin/bf_riblt.rs"

[[bin]]
name = "pinsketch"
path = "src/bin/pinsketch.rs"

[[bin]]
name = "full_state_transfer"
path = "src/bin/full_state_transfer.rs"

[[bin]]
name = "set_generator"
path = "src/bin/set_generator.rs"
